### ISSUE TITLE
Required information

### ISSUE THREAD

**Issue by rukku** [sakayph/pending-routes#1]
Hi, 

What is the minimum that you require of a contribution? Do you need both the stops and the linestring of the route or would it be possible to just send the linestring? (For routes that are already in the database but don't have their proper shapes yet).

Thanks!

**Comment by thatsmydoing** [comment]
Either is fine. For new routes, with no definite stops, you can just approximate where most people get on and off, but just the linestring is fine as well. Indicating terminal stops would be good, though, if it's circular.

**Comment by rukku** [comment]
Got it. Thanks!

—
